"""Generate schema_vs_dictionary.sql from dd_v3.json (+ an optional baseline file).

    python gen_schema_sql.py <out.sql> [baseline.txt]
"""
import json, os, re, sys

SP = os.path.dirname(os.path.abspath(__file__))
dd = json.load(open(os.path.join(SP, 'dd_v3.json'), encoding='utf-8'))
out_path = sys.argv[1]
baseline = []
if len(sys.argv) > 2 and os.path.exists(sys.argv[2]):
    baseline = [l.rstrip('\n') for l in open(sys.argv[2], encoding='utf-8') if l.strip()]

tables = {n: t for n, t in dd['tables'].items() if t['columns'] or n == 'HITS_DELETED'}
tables['HITS_DELETED'] = dict(tables['HITS_DELETED'], columns=tables['HITS']['columns'])

def accept(t):
    """Dictionary type -> LIKE patterns matched against the DB type as shown (e.g. numeric(14))."""
    u = re.sub(r'\s+', ' ', t.strip().upper())
    STR = ['name']                      # catalog "name" (ibsecure tables) is fine for any string type
    m = re.fullmatch(r'VC ?(\d+)', u)
    if m: return [f'character varying({m.group(1)})'] + STR
    if u == 'VC': return ['character varying%', 'text'] + STR
    if u in ('TEXT', 'VC, TEXT'): return ['text'] + (['character varying%'] if ',' in u else []) + STR
    m = re.fullmatch(r'N ?(\d+)', u)
    if m: return [f'numeric({m.group(1)})']
    m = re.fullmatch(r'N (\d+), ?(\d+)', u)
    if m: return [f'numeric({m.group(1)},{m.group(2)})' if m.group(2) != '0' else f'numeric({m.group(1)})']
    if u == 'N': return ['numeric%', 'integer', 'bigint']
    if u == 'N, D': return ['numeric%', 'double precision']
    m = re.fullmatch(r'N (\d+), BIGINT', u)
    if m: return [f'numeric({m.group(1)})', 'bigint']
    if u in ('INT', 'INTEGER', 'I'): return ['integer']
    if u == 'BIGINT': return ['bigint']
    m = re.fullmatch(r'TSTZ ?(\d+)', u)
    if m: return [f'timestamp with time zone({m.group(1)})']
    if u == 'TZ': return ['timestamp with time zone%']
    if u.startswith('BYTEA'): return ['bytea']
    if u == 'INTVL': return ['interval']
    m = re.fullmatch(r'CHAR ?(\d+)', u)
    if m: return [f'character({m.group(1)})'] + STR
    if u == 'CHAR': return ['character%'] + STR
    if u == 'JSONB': return ['jsonb']
    if u == 'BOOLEAN': return ['boolean']
    if u == 'DATE': return ['date']
    raise SystemExit(f'unknown dictionary type: {t!r}')

def norm(col):
    c = col.upper().replace(' ', '')
    return re.sub(r'::(CHARACTERVARYING|TEXT|NUMERIC|BPCHAR)', '', c)

q = lambda s: "'" + str(s).replace("'", "''") + "'"
arr = lambda xs: 'ARRAY[' + ', '.join(q(x) for x in xs) + ']::text[]'

col_rows, key_rows = [], []
for tname, t in tables.items():
    for i, c in enumerate(t['columns'], 1):
        col_rows.append(f"({q(tname)}, {q(c['name'].upper())}, {i}, {q(c['type'])}, {arr(accept(c['type']))}, {q(c['null'])})")
    for k in t['keys']:
        key_rows.append(f"({q(tname)}, {q(k['kind'])}, {q(k['name'].upper())}, {arr([norm(x) for x in k['columns']])}, {q(k['ref'].upper())})")
view_rows = [f'({q(v)})' for v in dd['views']]
base_rows = [f'({q(b)})' for b in baseline]

sql = f"""-- =============================================================================
-- schema_vs_dictionary.sql - compare this VM's IBIS schema to the data dictionary
--
-- Reference: DES35-00011 IBIS Database 6.0 - Data Dictionary, version 2.0 (2025-05-28):
--   {len(tables)} tables / {len(col_rows)} columns, {len(key_rows)} keys (PK/UK/FK), {len(view_rows)} views.
-- Checks every documented table (in ibisl0/ibisl1, or esi/ibsecure for the few that live
-- there): column existence, type/length, Mandatory/Optional; key names, columns and FK
-- targets; and that each documented view exists. Tables that are not in the dictionary,
-- and the leftover VAL (oid) columns, are ignored.
--
-- Each difference is printed as "known" (in the accepted baseline below, {len(base_rows)} entries)
-- or "NEW". The script ends with an ERROR if there is any NEW difference, so psql exits
-- non-zero (with ON_ERROR_STOP) - that is how the pipeline tells pass from fail.
--
-- Read-only: it only reads the catalog; its work tables are TEMP tables, gone at disconnect.
--   psql -h <host> -p 1815 -U dja -d ibis -f schema_vs_dictionary.sql
--
-- GENERATED by gen_schema_sql.py from the dictionary PDF - regenerate rather than hand-edit
-- the data sections; the baseline is the part meant to be reviewed and edited.
-- =============================================================================
\\set ON_ERROR_STOP 1
\\pset footer off
SET client_min_messages = warning;
SET statement_timeout = 0;

CREATE TEMP TABLE dd_col (tbl text, col text, ord int, dict_type text, accept text[], nullability text);
CREATE TEMP TABLE dd_key (tbl text, kind text, name text, cols text[], ref text);
CREATE TEMP TABLE dd_view (name text);
CREATE TEMP TABLE baseline (line text PRIMARY KEY);

-- ---------------------------------------------------------------- dictionary: columns
INSERT INTO dd_col VALUES
{(','+chr(10)).join(col_rows)};

-- ---------------------------------------------------------------- dictionary: keys
INSERT INTO dd_key VALUES
{(','+chr(10)).join(key_rows)};

-- ---------------------------------------------------------------- dictionary: views
INSERT INTO dd_view VALUES
{(','+chr(10)).join(view_rows)};

-- ---------------------------------------------------------------- accepted baseline
-- One line per accepted difference: "<category> | <object> | <detail>", exactly as printed.
""" + (f"INSERT INTO baseline VALUES\n{(','+chr(10)).join(base_rows)};\n" if base_rows else "-- (empty)\n") + r"""
-- ---------------------------------------------------------------- this VM
CREATE TEMP TABLE ctx AS
SELECT (SELECT nspname FROM pg_namespace WHERE nspname ~ '^ibisl[0-9]$' ORDER BY nspname LIMIT 1) AS ibis_schema;
DO $$ BEGIN
   IF (SELECT ibis_schema FROM ctx) IS NULL THEN RAISE EXCEPTION 'No ibisl<n> schema found in this database'; END IF;
END $$;

-- where each documented table is: the ibis schema first, else esi / ibsecure
CREATE TEMP TABLE db_tab AS
SELECT d.tbl, x.oid, x.nspname
  FROM (SELECT DISTINCT tbl FROM dd_col) d
  LEFT JOIN LATERAL (
        SELECT c.oid, n.nspname
          FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE c.relname = lower(d.tbl) AND c.relkind IN ('r','p') AND NOT c.relispartition
           AND n.nspname IN ((SELECT ibis_schema FROM ctx), 'esi', 'ibsecure')
         ORDER BY (n.nspname = (SELECT ibis_schema FROM ctx)) DESC
         LIMIT 1) x ON true;

CREATE TEMP TABLE db_col AS
SELECT t.tbl, upper(c.column_name) AS col, c.is_nullable,
       CASE WHEN c.data_type IN ('character varying','character') AND c.character_maximum_length IS NOT NULL
                 THEN c.data_type || '(' || c.character_maximum_length || ')'
            WHEN c.data_type = 'numeric' AND c.numeric_precision IS NOT NULL
                 THEN 'numeric(' || c.numeric_precision || CASE WHEN c.numeric_scale <> 0 THEN ',' || c.numeric_scale ELSE '' END || ')'
            WHEN c.data_type LIKE 'timestamp%' AND c.datetime_precision IS NOT NULL
                 THEN c.data_type || '(' || c.datetime_precision || ')'
            ELSE c.data_type END AS typ
  FROM db_tab t
  JOIN information_schema.columns c ON c.table_schema = t.nspname AND c.table_name = lower(t.tbl)
 WHERE t.oid IS NOT NULL;

-- keys: PK/UK constraints and plain unique indexes (columns or expressions from the index),
-- and FKs without the per-partition clones PostgreSQL adds (conparentid <> 0)
CREATE TEMP TABLE db_key AS
SELECT t.tbl, i.relname AS name, COALESCE(con.contype::text, 'ui') AS kind,
       (SELECT array_agg(regexp_replace(upper(replace(pg_get_indexdef(x.indexrelid, k, true), ' ', '')),
                                        '::(CHARACTERVARYING|TEXT|NUMERIC|BPCHAR)', '', 'g') ORDER BY k)
          FROM generate_series(1, x.indnkeyatts) k) AS cols,
       (SELECT string_agg(pg_get_indexdef(x.indexrelid, k, true), ',' ORDER BY k)
          FROM generate_series(1, x.indnkeyatts) k) AS cols_raw,
       ''::text AS ref
  FROM db_tab t
  JOIN pg_index x ON x.indrelid = t.oid AND x.indisunique
  JOIN pg_class i ON i.oid = x.indexrelid
  LEFT JOIN pg_constraint con ON con.conindid = x.indexrelid AND con.conrelid = t.oid AND con.contype IN ('p','u')
UNION ALL
SELECT t.tbl, con.conname, 'f',
       (SELECT array_agg(upper(a.attname::text) ORDER BY k.ord) FROM unnest(con.conkey) WITH ORDINALITY k(att, ord)
          JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.att),
       (SELECT string_agg(a.attname::text, ',' ORDER BY k.ord) FROM unnest(con.conkey) WITH ORDINALITY k(att, ord)
          JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.att),
       COALESCE((SELECT relname::text FROM pg_class WHERE oid = con.conindid), '')
  FROM db_tab t
  JOIN pg_constraint con ON con.conrelid = t.oid AND con.contype = 'f' AND con.conparentid = 0;

CREATE TEMP TABLE diff (category text, object text, detail text);

-- ---------------------------------------------------------------- tables and columns
INSERT INTO diff
SELECT 'table missing', t.tbl, NULL FROM db_tab t WHERE t.oid IS NULL;

INSERT INTO diff
SELECT 'column missing', d.tbl || '.' || d.col, d.dict_type
  FROM dd_col d JOIN db_tab t ON t.tbl = d.tbl AND t.oid IS NOT NULL
 WHERE NOT EXISTS (SELECT 1 FROM db_col c WHERE c.tbl = d.tbl AND c.col = d.col);

INSERT INTO diff
SELECT 'type differs', d.tbl || '.' || d.col, 'dictionary ' || d.dict_type || ' / DB ' || c.typ
  FROM dd_col d JOIN db_col c ON c.tbl = d.tbl AND c.col = d.col
 WHERE NOT (c.typ LIKE ANY (d.accept));

INSERT INTO diff
SELECT 'dictionary Mandatory, DB nullable', d.tbl || '.' || d.col, NULL
  FROM dd_col d JOIN db_col c ON c.tbl = d.tbl AND c.col = d.col
 WHERE d.nullability = 'mandatory' AND c.is_nullable = 'YES';

INSERT INTO diff
SELECT 'dictionary Optional, DB NOT NULL', d.tbl || '.' || d.col, NULL
  FROM dd_col d JOIN db_col c ON c.tbl = d.tbl AND c.col = d.col
 WHERE d.nullability = 'optional' AND c.is_nullable = 'NO';

INSERT INTO diff
SELECT 'column not in dictionary', c.tbl || '.' || c.col, c.typ
  FROM db_col c
 WHERE c.col <> 'VAL'          -- leftover large-object column (IBD-859), ignored on purpose
   AND NOT EXISTS (SELECT 1 FROM dd_col d WHERE d.tbl = c.tbl AND d.col = c.col);

-- ---------------------------------------------------------------- keys
CREATE TEMP TABLE key_match AS
SELECT k.tbl, k.kind, k.name, k.cols, k.ref,
       byname.name AS db_name, byname.cols AS db_cols, byname.ref AS db_ref,
       bycols.name AS same_cols_name
  FROM dd_key k
  JOIN db_tab t ON t.tbl = k.tbl AND t.oid IS NOT NULL
  LEFT JOIN LATERAL (
        SELECT b.* FROM db_key b
         WHERE b.tbl = k.tbl AND upper(b.name) = k.name
           AND b.kind = ANY (CASE k.kind WHEN 'p' THEN ARRAY['p','ui'] WHEN 'u' THEN ARRAY['u','ui'] ELSE ARRAY['f'] END)
         LIMIT 1) byname ON true
  LEFT JOIN LATERAL (
        SELECT b.name FROM db_key b
         WHERE byname.name IS NULL AND b.tbl = k.tbl AND b.cols = k.cols
           AND b.kind = ANY (CASE k.kind WHEN 'p' THEN ARRAY['p','ui'] WHEN 'u' THEN ARRAY['u','ui'] ELSE ARRAY['f'] END)
         ORDER BY b.kind, b.name
         LIMIT 1) bycols ON true;

INSERT INTO diff
SELECT 'key named differently', tbl || '.' || name, 'DB ' || same_cols_name
  FROM key_match WHERE db_name IS NULL AND same_cols_name IS NOT NULL;

INSERT INTO diff
SELECT 'key missing', tbl || '.' || name, kind || ' (' || array_to_string(cols, ',') || ')'
  FROM key_match WHERE db_name IS NULL AND same_cols_name IS NULL;

INSERT INTO diff
SELECT 'key columns differ', tbl || '.' || name,
       'dictionary (' || array_to_string(cols, ',') || ') / DB (' || array_to_string(db_cols, ',') || ')'
  FROM key_match WHERE db_name IS NOT NULL AND db_cols IS DISTINCT FROM cols;

INSERT INTO diff
SELECT 'foreign key target differs', tbl || '.' || name, 'dictionary ' || ref || ' / DB ' || COALESCE(NULLIF(db_ref, ''), '?')
  FROM key_match WHERE db_name IS NOT NULL AND kind = 'f' AND ref <> '' AND upper(COALESCE(db_ref, '')) <> ref;

INSERT INTO diff
SELECT 'key not in dictionary', b.tbl || '.' || b.name, b.kind || ' (' || b.cols_raw || ')'
  FROM db_key b
 WHERE b.kind IN ('p','u','f')
   AND NOT EXISTS (SELECT 1 FROM key_match m WHERE m.tbl = b.tbl AND (m.db_name = b.name OR m.same_cols_name = b.name));

-- ---------------------------------------------------------------- views
INSERT INTO diff
SELECT 'view missing', v.name, NULL
  FROM dd_view v
 WHERE NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relkind IN ('v','m') AND upper(c.relname) = v.name
                      AND n.nspname NOT IN ('ibishits','pg_catalog','information_schema'));

-- ---------------------------------------------------------------- result
CREATE TEMP TABLE result AS
SELECT CASE WHEN b.line IS NULL THEN 'NEW' ELSE 'known' END AS status, d.category, d.object, d.detail,
       d.category || ' | ' || d.object || COALESCE(' | ' || d.detail, '') AS line
  FROM diff d LEFT JOIN baseline b ON b.line = d.category || ' | ' || d.object || COALESCE(' | ' || d.detail, '');

\echo
\echo Differences against the data dictionary (NEW first):
SELECT status, category, object, detail FROM result ORDER BY status = 'known', category, object;

SELECT 'SCHEMA CHECK ' || CASE WHEN count(*) FILTER (WHERE status = 'NEW') = 0 THEN 'PASSED' ELSE 'FAILED' END
       || ' on ' || (SELECT ibis_schema FROM ctx) || ': '
       || count(*) FILTER (WHERE status = 'NEW') || ' NEW, '
       || count(*) FILTER (WHERE status = 'known') || ' known difference(s)' AS summary
  FROM result;

DO $$
DECLARE n int := (SELECT count(*) FROM result WHERE status = 'NEW');
BEGIN
   IF n > 0 THEN
      RAISE EXCEPTION 'Schema check FAILED: % NEW difference(s) against the data dictionary', n;
   END IF;
END $$;
"""
open(out_path, 'w', encoding='utf-8', newline='\n').write(sql)
print(f'wrote {out_path}: {len(col_rows)} columns, {len(key_rows)} keys, {len(view_rows)} views, {len(base_rows)} baseline lines')
